input_path: /work/hdd/bdsh/dzhao3/data/sample
output_path: /work/hdd/bdsh/dzhao3/output
models:
  formula_detection:
    model_name: formula_detection_yolo
    model_path: models/MFD/YOLO/yolo_v8_ft.pt
    img_size: 1280
    conf_thres: 0.10
    iou_thres: 0.20
    batch_size: 1
    visualize: True
  layout_detection:
    model_name: layout_detection_layoutlmv3
    model_path: models/Layout/LayoutLMv3/model_final.pth